name: Build and test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Init CMake
      run: cmake .
    - name: Build
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Linux executable
        path: build/tooreadable
    - name: Run tests
      run: ./tests
