name: Build and test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./build
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'
    - name: Check out the code
      uses: actions/checkout@v2
    - run: tree ..
    - name: Init CMake
      run: cmake .
    - name: Build
      run: make
    - name: Run tests
      run: ./tests
